[package]
name = "dorf_hero"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_tilemap = "0.4.0"
rand = "0.8.3"
pathfinding = "2.1.2"
